# Setting up Atlas.ai 

You should ensure that the `DATA_PATH` in `config.ini` matches whatever you set as the `output_directory` when you run `atlas_data.py`.

Also, ensure that `URL` in `config.ini` matches your development or production server (e.g. `http://localhost:8080` or `https://model-service.worldmodelers.com`).